import mongoose from "mongoose";
const { ObjectId, Schema } = mongoose;

/**
 * Payroll Settings — the Payroll Policy Engine. Brand-wide singleton
 * (`{brand}` unique, same convention as EmployeeSettings/AttendanceSettings).
 * Module 13 of the fixed 14-module HR rollout.
 *
 * This is POLICY, not CALCULATION — it does not compute a single payroll
 * amount itself. `hr/payroll` (pre-existing, mounted, confirmed pure CRUD
 * with zero calculation logic — HR_TECHNICAL_DEBT.md HD-013) is where a
 * future calculation engine would read these settings from; that engine is
 * explicitly NOT built in this rollout (HD-013/HD-015/HD-018 all point to
 * "Payroll's own future turn," which is outside this rollout's fixed
 * 14-module scope — see PAYROLL_SETTINGS.module.md §1).
 *
 * Single Source of Truth note: `cycle`/`defaults`/`automation` below
 * ABSORB and REPLACE `EmployeeSettings.payroll` (defaultSalaryType/
 * defaultCurrency/autoGeneratePayroll/payrollCycleDay), which is REMOVED
 * from that model in this same turn — see HR_TECHNICAL_DEBT.md HD-020.
 * Payroll cycle policy has exactly one home now.
 */

const accountRefSchema = { type: ObjectId, ref: "Account", default: null };

const payrollSettingsSchema = new Schema(
  {
    brand: { type: ObjectId, ref: "Brand", required: true, unique: true },

    // ===============================
    // Payroll Cycle
    // ===============================
    cycle: {
      frequency: { type: String, enum: ["monthly", "biweekly", "weekly", "daily"], default: "monthly" },
      // Day of the period after which attendance/leave/transaction data for
      // that period is considered final (subject to lockPolicy below).
      // Meaningless for "daily" frequency — validated as optional then.
      cutOffDay: { type: Number, min: 1, max: 31, default: 25 },
      // Day the payroll period is officially closed/calculated.
      closingDay: { type: Number, min: 1, max: 31, default: 28 },
      // Day employees are actually paid — may fall in the following month
      // (e.g. cutOffDay 25, payDay 5 of next month), which is why payDay is
      // NOT required to be numerically >= cutOffDay/closingDay (see service
      // validation — it only rejects payDay === cutOffDay, an unambiguous
      // contradiction, not "payDay is next month").
      payDay: { type: Number, min: 1, max: 31, default: 1 },
    },

    // ===============================
    // Defaults (absorbed from EmployeeSettings.payroll — HD-020)
    // ===============================
    defaults: {
      salaryType: { type: String, enum: ["monthly", "weekly", "daily", "hourly"], default: "monthly" },
      currency: { type: String, trim: true, uppercase: true, minlength: 3, maxlength: 3, default: "EGP" },
    },

    // ===============================
    // Automation & Approval Workflow
    // ===============================
    automation: {
      autoGenerate: { type: Boolean, default: false },
      // Day of the cycle automatic generation would run — reserved, no
      // scheduled job exists yet (see module doc §12).
      autoGenerateDay: { type: Number, min: 1, max: 31, default: null },
    },

    approvalWorkflow: {
      requireApproval: { type: Boolean, default: true },
      // A second, optional finance-level approval tier beyond HR's own —
      // reserved, no distinct enforcement point exists yet (Payroll itself
      // has no calculation engine to gate — see module doc §12).
      requireFinanceApproval: { type: Boolean, default: false },
    },

    // ===============================
    // Lock / Retroactive Policy
    // ===============================
    lockPolicy: {
      // Days after `cycle.closingDay` before a calculated (but not yet
      // approved) payroll period is automatically locked against further
      // attendance/leave/transaction changes. 0 = no automatic lock.
      lockAfterDays: { type: Number, min: 0, default: 0 },
      allowRetroactiveAdjustment: { type: Boolean, default: false },
      // Forced to 0 when allowRetroactiveAdjustment is false — see the
      // pre-save hook, same consistency pattern already used for
      // EmployeeSettings.leavePolicy's carry-forward fields.
      retroactiveWindowDays: { type: Number, min: 0, default: 0 },
      allowBackdatedAttendance: { type: Boolean, default: true },
      allowBackdatedLeave: { type: Boolean, default: true },
    },

    // ===============================
    // Rounding Policy
    // ===============================
    roundingPolicy: {
      method: { type: String, enum: ["none", "nearest", "up", "down"], default: "nearest" },
      precision: { type: Number, min: 0, max: 4, default: 2 },
    },

    // ===============================
    // Tax / Insurance Brand-Wide Defaults
    // ===============================
    // Distinct from EmployeeFinancialProfile.governmentInfo (module 9),
    // which holds the PER-EMPLOYEE rate once known — these are the brand
    // default an employee's profile falls back to when it hasn't set its
    // own rate. A real gap before this turn: EmployeeFinancialProfile had
    // no brand-wide default to inherit from at all.
    taxDefaults: {
      defaultIncomeTaxRatePercentage: { type: Number, min: 0, max: 100, default: 0 },
      defaultSocialInsuranceRatePercentage: { type: Number, min: 0, max: 100, default: 0 },
      // The EMPLOYER's own contribution rate (on top of, not deducted from,
      // the employee's pay) — a distinct concept EmployeeFinancialProfile
      // never modeled at all. Reserved: no calculation consumer yet.
      employerContributionRatePercentage: { type: Number, min: 0, max: 100, default: 0 },
    },

    // ===============================
    // Accounting Integration (architecture only — see module doc §7)
    // ===============================
    // Every account reference is optional and unvalidated against a chart
    // of accounts structure beyond "exists, belongs to this brand, and
    // allows posting" (service.js) — no journal-entry generation exists
    // yet anywhere in this project (deferred project-wide, consistent with
    // every other HR module in this rollout).
    accountingIntegration: {
      salaryExpenseAccount: accountRefSchema,
      payrollPayableAccount: accountRefSchema,
      advanceAccount: accountRefSchema,
      loanAccount: accountRefSchema,
      taxPayableAccount: accountRefSchema,
      insurancePayableAccount: accountRefSchema,
      cashAccount: accountRefSchema,
      bankAccount: accountRefSchema,
      serviceChargeLiabilityAccount: accountRefSchema,
      tipsPayableAccount: accountRefSchema,
      employerContributionExpenseAccount: accountRefSchema,
    },

    // ===============================
    // Restaurant Operations
    // ===============================
    // Multiple payroll calendars per branch (e.g. kitchen staff on a
    // weekly cycle while office staff are monthly) is a real restaurant
    // need this turn's protocol named explicitly, but a full multi-calendar
    // engine is out of this turn's bounded scope — reserved flag only, see
    // module doc §12.
    allowBranchCycleOverride: { type: Boolean, default: false },

    // ===============================
    // Audit
    // ===============================
    createdBy: { type: ObjectId, ref: "UserAccount", default: null },
    updatedBy: { type: ObjectId, ref: "UserAccount", default: null },

    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: ObjectId, ref: "UserAccount", default: null },
  },
  { timestamps: true, versionKey: false },
);

// Note: no extra `.index({brand:1})` — `unique: true` on `brand` above
// already creates that index (same convention as EmployeeSettings/
// AttendanceSettings).

payrollSettingsSchema.pre("save", function (next) {
  if (!this.lockPolicy.allowRetroactiveAdjustment) {
    this.lockPolicy.retroactiveWindowDays = 0;
  }

  next();
});

export default mongoose.model("PayrollSettings", payrollSettingsSchema);
