import inventorySettingsService from "../inventory-settings/inventory-settings.service.js";
import purchaseRequestService from "../../purchasing/purchase-request/purchase-request.service.js";
import PurchaseRequestModel from "../../purchasing/purchase-request/purchase-request.model.js";

/**
 * V5.2 Enterprise Replenishment & Reorder Engine.
 *
 * Subscribes to `DomainEvent.INVENTORY_BELOW_REORDER_POINT` (emitted by
 * warehouse-document.service.js#postDocument after any outbound movement leaves a balance at or
 * below the item's `minThreshold`) — no polling, no scheduled job, per the platform's
 * event-driven mandate. Registered once at boot by `server/utils/registerEventHandlers.js`.
 *
 * Two independent gates must both be satisfied before a PurchaseRequest is auto-created:
 *   1. Brand/branch level: `InventorySettings.autoGenerateReorderRequests` — the owner's global
 *      kill switch. Off by default; an item cannot opt itself into auto-purchasing if the brand
 *      hasn't turned this feature on.
 *   2. Item level: `StockItem.replenishmentPolicy` — NONE (no action), NOTIFY_ONLY (logged, no
 *      document created — this platform has no notification engine yet, see the honest limitation
 *      noted in SUPPLY_CHAIN_FINAL_AUDIT.md), or AUTO_PURCHASE_REQUEST.
 *
 * Idempotent by construction: before creating a PurchaseRequest it checks for an existing
 * still-open one (Draft/Submitted/Approved) referencing the same stock item on this brand/branch
 * — a burst of outbound movements against the same low-stock item (e.g. several POS sales in a
 * row) produces at most one open request, not one per movement.
 *
 * Deliberately NOT built this pass: auto-drafting a full PurchaseOrder (the prompt's "Auto Draft
 * Purchase Order" option), Economic Order Quantity calculation, and lead-time-aware timing (order
 * far enough ahead that the replenishment arrives before stockout, not only after the threshold is
 * already breached). `StockItem.leadTimeDays`/`safetyStock` exist on the schema so a future pass
 * can build genuine EOQ/lead-time logic on top without another migration — the fields are real,
 * the algorithm using them is not yet.
 */
const OPEN_PR_STATUSES = ["Draft", "Submitted", "Approved"];

class ReplenishmentEngine {
  async handleBelowReorderPoint({ brand, branch, stockItem, warehouse, balance, postedBy }) {
    try {
      await this._process({ brand, branch, stockItem, warehouse, balance, postedBy });
    } catch (err) {
      // Best-effort by design (domainEvents.js's documented convention) — a Replenishment Engine
      // failure must never be allowed to undo or block the stock movement that already committed.
      // eslint-disable-next-line no-console
      console.error(`[replenishment.service] Failed to process reorder trigger for stockItem ${stockItem?._id}: ${err.message}`);
    }
  }

  async _process({ brand, branch, stockItem, warehouse, balance, postedBy }) {
    const policy = stockItem.replenishmentPolicy || "NONE";
    if (policy === "NONE") return;

    if (policy === "NOTIFY_ONLY") {
      this._notify(stockItem, balance);
      return;
    }

    // policy === "AUTO_PURCHASE_REQUEST"
    const settings = await inventorySettingsService.resolveForPosting(brand, branch);
    if (!settings.autoGenerateReorderRequests) {
      // Item wants auto-purchasing but the brand hasn't enabled the feature — degrade to a
      // notification rather than silently doing nothing (the low-stock condition is still real).
      this._notify(stockItem, balance);
      return;
    }

    const alreadyOpen = await PurchaseRequestModel.exists({
      brand,
      branch,
      status: { $in: OPEN_PR_STATUSES },
      "items.stockItem": stockItem._id,
    });
    if (alreadyOpen) return;

    const quantity =
      stockItem.reorderQuantity > 0
        ? stockItem.reorderQuantity
        : Math.max((stockItem.maxThreshold || 0) - balance.quantity, stockItem.safetyStock || 0, 1);

    await purchaseRequestService.create({
      brandId: brand,
      branchId: branch,
      createdBy: postedBy,
      data: {
        branch,
        requestedBy: postedBy,
        items: [{ stockItem: stockItem._id, quantity }],
        justification:
          `Auto-generated by the Replenishment Engine: balance in warehouse ${warehouse} fell to ` +
          `${balance.quantity} (reorder point ${stockItem.minThreshold}).`,
      },
    });
  }

  _notify(stockItem, balance) {
    // No notification engine exists in this platform yet (confirmed during the V5.2 audit) — this
    // is an honest stub, not a disguised no-op: it's the single place that integration will be
    // wired in once one exists, and in the meantime it's at least visible in server logs.
    // eslint-disable-next-line no-console
    console.warn(`[replenishment.service] Low stock: item ${stockItem._id} at ${balance.quantity} (reorder point ${stockItem.minThreshold}).`);
  }
}

export default new ReplenishmentEngine();
